#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

readonly folder=terraform

get() {
  kwalletcli -q -f "$folder" -e "$1" || echo '{}'
}

store() {
  kwalletcli -q -f "$folder" -e "$1" -P
}

forget() {
  kwalletcli -q -f "$folder" -e "$1" -p "{}"
}

[[ $# -eq 2 ]] && "$1" "$2" && exit

if ! type kwalletcli &>/dev/null; then
  echo "kwalletcli not found"
  exit 1
fi

cat <<EOF >&2
Usage: $(basename "$0") <command> <hostname>

Where command could be:
    get       Retrieve the credentials for the given hostname
    store     Store new credentials for the given hostname
    forget    Delete any stored credentials for the given hostname
EOF
exit 1
